name: Auto Update Data MBG

on:
  schedule:
    # Berjalan otomatis setiap jam 06:00 WIB Pagi
    - cron: '0 23 * * *'
  
  # Memungkinkan jalankan manual lewat tombol "Run Workflow" di GitHub
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Menggunakan versi v4 agar mendukung Node.js terbaru
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Menggunakan versi v5 agar mendukung Node.js terbaru
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Jalankan Script Scraper Python
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python updater.py

      - name: Commit dan Push Perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.js
          git commit -m "🤖 Auto-update data kasus baru" || echo "Tidak ada perubahan"
          git push
